# Generated by Django 3.2.12 on 2022-08-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhapp', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='hhapp.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(to='hhapp.Tag'),
        ),
    ]
