# Generated by Django 3.2.12 on 2022-07-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhapp', '0004_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='articles',
            name='published',
            field=models.CharField(max_length=20),
        ),
    ]
