# Generated by Django 3.2.12 on 2022-08-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhapp', '0005_auto_20220811_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
